package io.github.maniramezan.kenwork.network

/**
 * A single observed network request outcome, for telemetry/analytics. The Kotlin counterpart of
 * Novalingo's `NetworkTelemetryEvent`, kept transport-agnostic so any analytics backend can
 * consume it.
 *
 * @property endpointId a normalized, low-cardinality endpoint identifier (e.g. `videos/:id`).
 * @property method the HTTP method.
 * @property durationMs wall-clock duration of the attempt(s).
 * @property statusCode the final HTTP status, or `null` if the request never completed.
 * @property errorType a coarse error classification, or `null` on success.
 * @property isRetryable whether the failure is considered transient.
 * @property attempt the 0-based attempt index this event describes (0 = first try). A request that
 *   is retried emits one event per failed attempt followed by a final success/failure event.
 * @property isFinalAttempt whether this event is the last one for its logical request — `true` for
 *   a success, or for a failure the [RetryPolicy] declined to retry; `false` for a failed attempt
 *   that's about to be retried. Lets a metrics bridge emit exactly one request-duration observation
 *   per logical request (filter on `isFinalAttempt`) while still using every event, including
 *   non-final ones, for a per-attempt/retry-count counter.
 */
public class NetworkEvent(
    public val endpointId: String,
    public val method: String,
    public val durationMs: Long,
    public val statusCode: Int? = null,
    public val errorType: String? = null,
    public val isRetryable: Boolean = false,
    public val attempt: Int = 0,
    public val isFinalAttempt: Boolean = true,
) {
    /** Whether this event represents a successful (2xx) request. */
    public val isSuccess: Boolean get() = errorType == null && statusCode in 200..299

    /** Binary-compatibility shim for the pre-0.4 constructor. */
    @Deprecated(
        "Binary-compatibility shim for pre-0.4 callers; use the primary constructor.",
        level = DeprecationLevel.HIDDEN,
    )
    public constructor(
        endpointId: String,
        method: String,
        durationMs: Long,
        statusCode: Int? = null,
        errorType: String? = null,
        isRetryable: Boolean = false,
        attempt: Int = 0,
    ) : this(endpointId, method, durationMs, statusCode, errorType, isRetryable, attempt, true)

    public operator fun component1(): String = endpointId

    public operator fun component2(): String = method

    public operator fun component3(): Long = durationMs

    public operator fun component4(): Int? = statusCode

    public operator fun component5(): String? = errorType

    public operator fun component6(): Boolean = isRetryable

    public operator fun component7(): Int = attempt

    /** Preserves the copy method and `copy$default` bridge generated by the pre-0.4 data class. */
    public fun copy(
        endpointId: String = this.endpointId,
        method: String = this.method,
        durationMs: Long = this.durationMs,
        statusCode: Int? = this.statusCode,
        errorType: String? = this.errorType,
        isRetryable: Boolean = this.isRetryable,
        attempt: Int = this.attempt,
    ): NetworkEvent = NetworkEvent(endpointId, method, durationMs, statusCode, errorType, isRetryable, attempt, isFinalAttempt)

    /** Copies an event while explicitly changing whether it is the final attempt. */
    @Suppress("LongParameterList")
    public fun copy(
        endpointId: String,
        method: String,
        durationMs: Long,
        statusCode: Int?,
        errorType: String?,
        isRetryable: Boolean,
        attempt: Int,
        isFinalAttempt: Boolean,
    ): NetworkEvent = NetworkEvent(endpointId, method, durationMs, statusCode, errorType, isRetryable, attempt, isFinalAttempt)

    override fun equals(other: Any?): Boolean =
        this === other ||
            other is NetworkEvent &&
            endpointId == other.endpointId &&
            method == other.method &&
            durationMs == other.durationMs &&
            statusCode == other.statusCode &&
            errorType == other.errorType &&
            isRetryable == other.isRetryable &&
            attempt == other.attempt &&
            isFinalAttempt == other.isFinalAttempt

    override fun hashCode(): Int {
        var result = endpointId.hashCode()
        result = 31 * result + method.hashCode()
        result = 31 * result + durationMs.hashCode()
        result = 31 * result + (statusCode ?: 0)
        result = 31 * result + (errorType?.hashCode() ?: 0)
        result = 31 * result + isRetryable.hashCode()
        result = 31 * result + attempt
        result = 31 * result + isFinalAttempt.hashCode()
        return result
    }

    override fun toString(): String =
        "NetworkEvent(endpointId=$endpointId, method=$method, durationMs=$durationMs, " +
            "statusCode=$statusCode, errorType=$errorType, isRetryable=$isRetryable, " +
            "attempt=$attempt, isFinalAttempt=$isFinalAttempt)"
}

/** Receives [NetworkEvent]s emitted by [NetworkClient]. Wire this to your analytics pipeline. */
public fun interface NetworkEventListener {
    public fun onEvent(event: NetworkEvent)
}
